sso-proxy:
  port: 9900
  bindAddress: 0.0.0.0
  sessionSetting:
    maxAge: 1800  # session的默认超时时间，单位秒
  iamBaseUrl: http://localhost:8080 #IAM外部SSO的base URL，浏览器SSO跳转时需要使用该URL
  internalIamBaseUrl: http://192.168.159.129:8080 #内部访问的URL，在同步clients时需要从内部调用。如果不设置，则使用iamBaseUrl
  oidcAuthCallbackUrl: http://localhost:9900/auth/callback # 申请token的回调地址，IAM会回调该地址再申请token
  globalPublicUris: # 不需要登录就可以调用的uri
    - "/auth"
    - "/auth/callback"
    - "/public/**"
    - "**.{js,json,jpg,ico,png}"
  oidcScopes:
    - openid
    - profile
    - email
  oidcClients:
    - realm: master # 在IAM上master realm下注册的client，并启用Service Account。以便进行client的自注册
      clientId: sso-proxy  # client created in master realm and has service account enabled
      secret: eUGbBI99r9P3kg8bIVcykq7YMnU741JG
      providerUrlPrefix: "{{ value .InternalIamBaseUrl .IamBaseUrl }}/realms/master" #如果internalIamBaseUrl不为空则使用，否则使用iamBaseUrl

  authenticators:
    #当前只支持一个keycloak，如果需要添加其他类型的，记得修改common.GetAuthenticator()逻辑
    - type: keycloak
      name: keycloak-authenticator
      url: "{{ value .InternalIamBaseUrl .IamBaseUrl }}"  #内部访问的URL，在同步clients时需要从内部调用。如果不设置，则使用{iamBaseUrl}
      syncClients:
        enabledOnStartup: true
        autoRegister: true # 如果realm下没有sso-proxy,自动注册
        registerSetting:
          clientId: sso-proxy
          name: sso-proxy
          generateSecret: true
          # secret: test  #将generateSecret设置为false， 可以手动设置secret
          enabled: true
          standardFlowEnabled: true
          serviceAccountsEnabled: false
          webOrigin:
            - "*"
          redirectURIs:
            - "*"

        pageParam: #分页查询的参数设置, first, max
          first: 0
          max: 100

  apps:
    - appId: cloud-portal
      loginPage: http://localhost:8088/login
      homePage: http://localhost:8088/home
      grantType: authorization_code

  reverseProxy:
    urlPrefix: /proxy  # 代理请求的base uri
    httpTransport:
      timeout: 10  # seconds
      keepAlive: 20 # seconds
      maxIdleConnections: 100 # seconds
      idleConnectionTimeout: 20 # seconds
      tls:
        handShakeTimeout: 10 # seconds
        expectContinueTimeout: 1 # seconds
        insecureSkipVerify: true # 忽略证书校验

    routes:
      # 请求路径: /proxy/iam/**, 格式：${reverseProxy.urlPrefix}/${routes.serviceName}
      - serviceName: iam
        url: "{{ .InternalIamBaseUrl }}" # the url of backend service
        publicUris: # 未经登录就可以调用的uri
          - "**/realms/**/departments-resource/**"
        filters: # filter用于过滤request或response,进行一些特殊处理
          - SetHeader: Host=localhost:8080, X-Forwarded-Host=localhost:8080, X-Forwarded-Proto=http # 转发的请求需要添加请求头， keycloak有LB部署的情况下读取X-Forwarded-Host，非LB的情况下读取Host
          - SetBearerToken: Bearer=iam.accessToken # 转发的请求携带IAM的access token. iam.accessToken or openstack.accessToken

  enableDevFeatures: false
  logSetting:
    logLevel: DEBUG
    logPath: /var/log/sso-proxy # 日志存放路径：${logPath}/${fileName}
    outputToConsole: true  # 是否同时将日志打印到控制台
    fileName: sso-proxy.log
    maxSizeInMB: 30   # 日志文件的体积
    maxAgeInDay: 30   # 最多保留天数
    maxBackups: 10    # 允许存在几个日志备份文件
    compress: true    # 是否压缩保存历史文件